# -*- coding: utf-8 -*-
"""smshtmlstreamlit.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1TbuqeYSWHaLsD_RhSgE-zbuPwxVAPZn9
"""

import streamlit as st
import pickle

# Load the classifier from the pickle file
with open('spam_classifier.pkl', 'rb') as f:
    spam_classifier = pickle.load(f)

# Define a function to make predictions
def predict(sentences):
    y_pred = spam_classifier.predict(sentences)
    return y_pred

# Set up some HTML to make the app look nicer
st.markdown("<h1 style='text-align: center;'>SMS Spam Detector</h1>", unsafe_allow_html=True)
st.markdown("<hr>", unsafe_allow_html=True)

# Create a text input for the user to enter a sentence
sentence = st.text_input('Enter an SMS message')

# Make a prediction when the user clicks a button
if st.button('Predict'):
    prediction = predict([sentence])[0]
    if prediction == 0:
        st.markdown("<h2 style='text-align: center; color: green;'>This message is not spam!</h2>", unsafe_allow_html=True)
    else:
        st.markdown("<h2 style='text-align: center; color: red;'>This message is spam!</h2>", unsafe_allow_html=True)